# Generated by Django 6.0.4 on 2026-04-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('achievements', models.TextField(blank=True, help_text='One bullet per line. These will be split into a list in the API.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Superadmin managed portfolio', max_length=80)),
                ('hero_title', models.CharField(default='I build polished digital experiences that feel effortless.', max_length=180)),
                ('hero_intro', models.CharField(default='Full-stack portfolio powered by Django + SQLite + Next.js', max_length=160)),
                ('hero_description', models.TextField(default='This site is fully manageable from a superadmin dashboard. Update projects, skills, timeline entries, and contact details without touching code.')),
                ('primary_cta_label', models.CharField(default='View Projects', max_length=40)),
                ('primary_cta_url', models.CharField(default='/projects', max_length=160)),
                ('secondary_cta_label', models.CharField(default='Contact Me', max_length=40)),
                ('secondary_cta_url', models.CharField(default='/work/contact', max_length=160)),
                ('highlight_title', models.CharField(default='Why this setup works', max_length=120)),
                ('highlight_body', models.TextField(default='Django admin gives the superadmin a familiar control center, while the public site stays fast and design-forward on the frontend.')),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home page',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('stack', models.CharField(help_text='Comma separated technologies, e.g. Next.js, Django, Tailwind', max_length=240)),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('highlight', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Your Name', max_length=120)),
                ('site_tagline', models.CharField(default='Designer, developer, and digital problem solver.', max_length=180)),
                ('seo_description', models.TextField(default='A modern portfolio website powered by Django and Next.js.')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('availability_text', models.CharField(default='Available for freelance and full-time opportunities.', max_length=160)),
                ('resume_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='Built for ambitious brands and thoughtful digital products.', max_length=180)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('website', 'Website'), ('mail', 'Mail')], default='website', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'author_name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('summary', models.CharField(blank=True, max_length=180)),
                ('level', models.CharField(choices=[('expert', 'Expert'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate')], default='advanced', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cms.skillgroup')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
