# Generated by Django 6.0.4 on 2026-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('color', models.CharField(choices=[('amber', 'Amber'), ('pink', 'Pink'), ('sky', 'Sky')], default='amber', max_length=20)),
                ('icon', models.CharField(choices=[('sparkles', 'Sparkles'), ('heart', 'Heart'), ('code', 'Code')], default='sparkles', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomeTechStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(choices=[('typescript', 'TypeScript'), ('react', 'React'), ('tailwind', 'Tailwind CSS'), ('framer-motion', 'Framer Motion'), ('nextjs', 'Next.js'), ('divider', 'Divider'), ('vscode', 'VS Code'), ('figma', 'Figma')], max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ManagedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=220)),
                ('caption', models.CharField(blank=True, max_length=80)),
                ('body_markdown', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='detail_description',
            field=models.CharField(default='Awareness to ease of access, User Interface consistency, and improved User Experience.', max_length=220),
        ),
        migrations.AddField(
            model_name='homepage',
            name='detail_title',
            field=models.CharField(default='Keen Eye for Spotting Small Details.', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='full_name',
            field=models.CharField(default='Enji Kusnadi', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='greeting',
            field=models.CharField(default='hi!', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='Enji', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='optimized_description',
            field=models.CharField(default='Writing clean code is a top priority while keeping it as optimized as possible.', max_length=220),
        ),
        migrations.AddField(
            model_name='homepage',
            name='optimized_title',
            field=models.CharField(default='Comprehensible and Optimized Code.', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_line_one',
            field=models.CharField(default='Beautiful', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_line_three_highlight',
            field=models.CharField(default='must.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_line_three_prefix',
            field=models.CharField(default='is a', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_line_two_prefix',
            field=models.CharField(default='inside', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_line_two_suffix',
            field=models.CharField(default='out', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='role',
            field=models.CharField(default='Front-End Developer', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='role_description',
            field=models.CharField(default='who loves intuitive, clean and modern UI design.', max_length=240),
        ),
    ]
