# Generated by Django 6.0.4 on 2026-04-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homefeaturecard_hometechstackitem_managedpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_name',
            field=models.CharField(default='Your Name', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='design_concept_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='figma_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_title',
            field=models.CharField(default='About Me', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='last_update_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_name',
            field=models.CharField(default='Your Name', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='role_title',
            field=models.CharField(default='Front-End Developer', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='source_code_url',
            field=models.URLField(blank=True),
        ),
    ]
