# Generated by Django 6.0.4 on 2026-04-10 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sitesettings_copyright_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_entry_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='template_zip',
            field=models.FileField(blank=True, help_text='Upload a static HTML/CSS/JS zip file with an index.html entry point.', upload_to='project_templates/zips/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
