# Generated by Django 6.0.4 on 2026-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_project_demo_entry_path_project_template_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a project cover image to display on the portfolio site.', upload_to='project_covers/'),
        ),
    ]
